import { DarkModeProvider } from '@/context/darkModeContext';
import './globals.css';
import { Header } from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <DarkModeProvider>
      <html lang="ru">
        <body>
          <Header />
          {/* отступ для fixed header */}
          <div className="mt-[72px] lg:mt-[88px]"></div>
          {children}
          <Footer />
        </body>
      </html>
    </DarkModeProvider>
  );
}
